### ISSUE TITLE
Release of Ruby version loosening logic

### ISSUE THREAD

**Issue by braydensterrett** [xlab-steampunk/redfish-client-ruby#2]
Hello,

My team is currently waiting on a new version of this gem to be cut so that we can consume it with Ruby 3.0.0. It appears that my colleagues PR has been merged which loosens the `required_ruby_version` but no new version of this gem has been released so that we can consume. Can someone help us get a new version out there so we can continue with our upgrade to Ruby 3.0.0? Please let me know if there's anyway I can help.

**Comment by tadeboro** [comment]
I am sorry for the delay. We had some troubles with the CI/CD that annoyed me just enough that I forgot to create a new release. https://rubygems.org/gems/redfish_client/versions/0.5.3 is out since a few minutes ago.

**Comment by braydensterrett** [comment]
@tadeboro appreciate you getting this done for us!
