### ISSUE TITLE
IBM POWER returns '200' for successful redfish auth

### ISSUE THREAD

**Issue by xray-sky** [xlab-steampunk/redfish-client-ruby#44]
redfish_client fails auth against an IBM POWER system, as it does not return 201 on successful auth.

```
$  curl -v -k -X POST -d '{"UserName": "admin", "Password": <password>}' https://<hostname>/redfish/v1/SessionService/Sessions                                 
*   Trying <ip>...
* Connected to <hostname> (<ip>) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: 9009-22A-<serial_nr>
> POST /redfish/v1/SessionService/Sessions HTTP/1.1
> Host: <hostname>
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 47
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 47 out of 47 bytes
< HTTP/1.1 200 OK
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Content-Security-Policy: allow 'self'
< Strict-Transport-Security: max-age=63072000
< Link: http://redfish.dmtf.org/schemas/v1/Session.v1_0_2.json; rel=describedby
< Content-Length: 277
< Content-Type: application/json
< Location: /redfish/v1/SessionService/Sessions/0
< X-Auth-Token: <valid_token>
< Date: Sat, 22 May 2004 05:30:53 GMT
< Server: lighttpd/1.4.41
< 
{
    "@odata.context": "/redfish/v1/$metadata#Session.Session",
    "@odata.id": "/redfish/v1/SessionService/Sessions/0",
    "@odata.type": "#Session.v1_0_2.Session",
    "Description": "Remote User Session",
    "Id": 0,
    "Name": "User Session",
    "UserName": "admin"
* Connection #0 to host <hostname> left intact
} $  

```

Give me a few days to do some more testing to determine if there are any other areas where return codes from a POWER system might be slightly different than expected, and whether any of the potential changes look problematic, and I'll submit a pull request.

**Comment by xray-sky** [comment]
PR https://github.com/xlab-si/redfish-client-ruby/pull/45

**Comment by vwbusguy** [comment]
It appears that Cisco does the same thing (returns 200 instead of 201): http://talk.manageiq.org/t/error-in-adding-redfish-supported-cisco-imc-server-in-manageiq/4633/8

**Comment by xray-sky** [comment]
For folks who are following this issue and maybe not the details in the PR, I'll summarize the status.

IBM accepted a PMR to fix their redfish implementation. They're taking their own time with it, but as I was anticipating a future need on our part we are still able to wait for them to eventually provide something. (i.e. it hasn't become more than a theoretical problem for us yet, as we're still waiting on Foreman to accept some code that would add Redfish support and make use of this module.)

**Comment by xray-sky** [comment]
POWER9 fixed: https://delivery04.dhe.ibm.com/sar/CMA/SFA/095bw/0/01VL940_061_027.html

POWER8 fix still promised.

**Comment by xray-sky** [comment]
POWER8 fixed: https://download4.boulder.ibm.com/sar/CMA/SFA/09cjs/0/01SV860_226_165.html

Closing.
