### ISSUE TITLE
Use this Redfish client without sessions

### ISSUE THREAD

**Issue by neomilium** [xlab-steampunk/redfish-client-ruby#7]
Depending on your needs, it may be interesting to only call directly the target endpoint, instead of starting with a login (ie. _Redfish_ sessions creation), call only one endpoint then logout to prevent from leaving sessions opened.

I would like to use this _Redfish_ client without sessions in Foreman.

To reach my goal, I used a trick to force `Root` to consider only basic auth as option.

See https://github.com/theforeman/smart-proxy/pull/895/files

Is there is someone in maintainers interested by this feature?

**Comment by matejart** [comment]
Thank you for this suggestion, @neomilium.

Unfortunately at this time, we are not taking feature requests. However, we'll be happy to review and merge any PRs that improve functionality and are of sufficient quality.

**Comment by ekohl** [comment]
@matejart I opened https://github.com/xlab-steampunk/redfish-client-ruby/pull/8 a while back. Could you please review it?
